services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=practice'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=spring'
    ports:
      - '5432:5432'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
